#!/bin/sh

apt-get -y install ant
apt-get -y install aumix
apt-get -y install byzanz
apt-get -y install chromium
apt-get -y install curl
apt-get -y install default-jdk
apt-get -y install gdmap
apt-get -y install gimp
apt-get -y install git
apt-get -y install gnupg
apt-get -y install gpicview
apt-get -y install graphviz
apt-get -y install iceweasel
apt-get -y install iptables-persistent
apt-get -y install keepassx
apt-get -y install libreoffice
apt-get -y install lightdm
apt-get -y install links2
apt-get -y install lp-solve
apt-get -y install lxrandr
apt-get -y install arandr
apt-get -y install lxterminal
apt-get -y install maven
apt-get -y install menu
apt-get -y install medit
apt-get -y install netselect-apt
apt-get -y install net-tools
apt-get -y install nitrogen
apt-get -y install nmap
apt-get -y install ntfs-3g
apt-get -y install obconf
apt-get -y install obmenu
apt-get -y install openbox
apt-get -y install orpie
apt-get -y install parted
apt-get -y install psmisc
apt-get -y install pulseaudio
apt-get -y install qpdfview
apt-get -y install rsync
apt-get -y install simplescreenrecorder
apt-get -y install scanimage
apt-get -y install stopwatch
apt-get -y install suckless-tools
apt-get -y install vim
apt-get -y install vlc
apt-get -y install vym
apt-get -y install wipe
apt-get -y install wireless-tools
apt-get -y install xfburn
apt-get -y install xfce4-screenshooter
apt-get -y install xinit
apt-get -y install xsane
apt-get -y install xserver-xorg-core
apt-get -y install xserver-xorg-input-all
apt-get -y install zip
apt-get -y install xdotool
apt-get -y install dia
apt-get -y install gtkhash
apt-get -y install pavucontrol
apt-get -y install filezilla
apt-get -y install gparted
apt-get -y install evince
apt-get -y install ristretto
apt-get -y install tint2
apt-get -y install conky
apt-get -y install cdw
apt-get -y remove xterm
apt autoremove
apt clean
